### ISSUE TITLE
[F.Rq.] Anchor nav buttons on headers

### ISSUE THREAD

**Issue by YoshiRulz** [adelikat/tasvideos#1677]
For example, GitHub's implementation looks like:
```html
<header>
	<a id="anchor-name"><svg class="anchor-nav-icon">...</svg></a>
	Header Text
</header>
```
```css
.anchor-nav-icon {
	visibility: hidden;
}
header:hover .anchor-nav-icon {
	visibility: visible;
}
```
That is, the anchor actually scrolls to the icon.
