### ISSUE TITLE
If possible prevent hyperlinks being overwritten by colour.

### ISSUE THREAD

**Issue by Spikestuff** [adelikat/tasvideos#1762]
Basically more of a security sort of thing where on the forums the hyperlinks can be hidden by the hex colours #FFFFFF/#2C3034 (and anything within the Saturation/Luminance field).

Should specify exactly with an example running red on 3 link types.
![image](https://github.com/TASVideos/tasvideos/assets/12412764/7f553e7f-1b44-4cbb-aa43-6e195f657a0e)

**Comment by YoshiRulz** [comment]
I think something like
```css
span:not(a span) { color: var(--span-color, currentColor); }
```
and using `style="--span-color: #AABBCC;"` would do it.
