### ISSUE TITLE
If a hyperlink is made, and a url is used to overwrite it. Display both.

### ISSUE THREAD

**Issue by Spikestuff** [adelikat/tasvideos#1776]
Word salad of a title, see the image for basically what I mean.

![image](https://github.com/TASVideos/tasvideos/assets/12412764/d5a43c3c-b540-4db9-86ed-44a83d6d15a8)

This is another "for security" reasons, especially more for the mobile device users who can't hover hyperlinks, and have to hold at each instance if they're paranoid.

**Comment by bigbass1997** [comment]
I could see someone writing a legit link like this as a way to shorten or hide the bulk of the link for the aesthetics.
```
[url=https://archive.org/download/foo/bar.mp3]archive.org[/url]
```
However, I could absolutely see a malicious actor doing this too.

---

So for this to work, I think we'd need to attempt to parse both strings as URLs ([the site currently doesn't do this](https://github.com/TASVideos/tasvideos/blob/63642c42248fcd07f2a2528fe24ad89a756c9ec2/TASVideos.ForumEngine/Node.cs#L100-L127) for either), and then ideally check if they point to different hosts. 

Also, to be clear, by "Display both" I guess we'd display both _as regular text?_

**Comment by YoshiRulz** [comment]
You could either emit the domain as rich text `<a href="...">...</a> <span class="domain-hint">(site.example)</span>`, or emit it as metadata `<span data-domain-hint="site.example"><a href="...">...</a></span>` and use CSS to render it:
```css
[data-domain-hint]::after {
	color: var(--bs-secondary-color);
	content: "(" attr(data-domain-hint) ")";
	font-size: 0.75em;
	padding-inline-start: 0.5em;
}
```
