### ISSUE TITLE
[Forums] If possible prevent hyperlinks being placed on less than 3 characters.

### ISSUE THREAD

**Issue by Spikestuff** [adelikat/tasvideos#2049]
Mostly forum anti-abuse, also one of the rarer type of abuses where a bot has placed a url link on a period.
Yes I know it would place an outgoing link icon, but it'd also help for the inbound links which is why I'm not being specific about it in the title.

**Comment by bigbass1997** [comment]
It's rare but sometimes when linking multiple things in a sequence, there could be cases where a legit user tries to place a hyperlink on 1 or 2 characters. Such as a [list](https://tasvideos.org/1001M) [of](https://tasvideos.org/1002M) [movies](https://tasvideos.org/1003M).

Preventing links on 1 character might be worth it though. Perhaps a more significant concern would be links on punctuation, spaces, or invalid characters?

**Comment by YoshiRulz** [comment]
I had a feeling there was a simple solution to this, and it's `min-width`.
```css
.postbody a {
	display: inline-block;
	min-width: 1em;
}
.postbody a:hover/*:not([rel~=external])*/ {
	text-decoration-inset: 0 -1em;
}
```
<img width="287" height="169" alt="Image" src="https://github.com/user-attachments/assets/5ff5dadd-c057-41db-8955-e33a3dc9b3a5" />
